# Generated by Django 4.0.5 on 2022-08-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(to='core.tags'),
        ),
        migrations.AddField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(to='core.article'),
        ),
    ]
