# Generated by Django 4.0.5 on 2022-08-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_subcategory_tags_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcategory',
            new_name='tags',
        ),
    ]
