# Generated by Django 4.0.5 on 2022-08-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_category_tags_alter_tags_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.tags'),
            preserve_default=False,
        ),
    ]
