# Generated by Django 4.0.5 on 2022-08-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_tags_articles_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
    ]
