# Generated by Django 4.0.5 on 2022-08-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
    ]
